name: odd
description: A speedrun platformer. Collect every coin as fast as you can.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.38.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/maps/
    - assets/sprites/Enemies/
    - assets/sprites/Objects/
    - assets/sprites/Tilesets/
